#!/bin/bash
#
#
#SBATCH --job-name=tape_data
#SBATCH --partition=compute
#SBATCH --time=8:00:00
#SBATCH --output=data_tape_comment_%j.log
#SBATCH --error=data_tape_error_%j.log
#SBATCH --mail-type=FAIL
#SBATCH --account=uo1075
module load cdo

y0=1 #first ensemble member
yn=50 #last ensemble member
scenario=historical

for ens_id in $(seq $y0 $yn); do
        cdo mergetime /work/uo1075/u241308/SMILE/MIROC6/tas/${scenario}/tas_Amon_MIROC6_${scenario}_r${ens_id}i1p1f1_gn_*.nc /work/uo1075/u241308/SMILE/MIROC6/tas/${scenario}/joker_${scenario}_ens_${ens_id}.nc
        cdo fldmean,weights=TRUE /work/uo1075/u241308/SMILE/MIROC6/tas/${scenario}/joker_${scenario}_ens_${ens_id}.nc /work/uo1075/u241308/SMILE/MIROC6/tas/${scenario}/joker_${scenario}_ens_${ens_id}_mean.nc
done

cdo merge /work/uo1075/u241308/SMILE/MIROC6/tas/${scenario}/joker_${scenario}_ens_*_mean.nc /work/uo1075/u241308/SMILE/MIROC6/tas/MIROC6_GMT_${scenario}_mm.nc
rm /work/uo1075/u241308/SMILE/MIROC6/tas/${scenario}/joker_${scenario}_*nc

